FROM python:3.11

#System Update
RUN apt update
RUN apt update -y

#Update pip
RUN pip install --upgrade pip

COPY ./requirements.txt /requirements.txt

#Install
RUN pip install -r /requirements.txt

RUN mkdir src

WORKDIR /src